trigger:
  batch: true
  branches:
    include:
      - main

stages:
  - stage: Build_Publish
    jobs:
      - job: Build
        pool:
          name: sripap1-local-pc
        steps:
          - template: build.yml
  
      - job: PublishBuildArtifacts
        pool:
          name: sripap1-local-pc
        steps:
          - template: publish.yml

  - stage: Deploy
    dependsOn: Build_Publish
    condition: succeeded()
    jobs:
      - deployment: DeployHitLevelDataProcessor
        displayName: Deploy - Hit Level Data Processor
        pool: 
          name: sripap1-local-pc
        environment: DeployHitLevelDataProcessor
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy.yml
                  parameters:
                    awsRegion: 'us-east-2'
                    awsCredentials: 'service_connection_psripathi_aws'
                    bucketName: 'acs-hit-level-data-store1'
                    cfnRoleArn: 'azdo-cfn-infa-role'
                    azdoArtifactPrefix: 'artifacts/hit_level_data_process_service'
                    lambdaServiceRoleARN: 'arn:aws:iam::684675566037:role/lambda-service-role'
